### ISSUE TITLE
program core because of server close connection

### ISSUE THREAD

**Issue by Chao-Zeng** [naver/arcus-c-client#164]
program core because memcache invoke abort()
arcus-c-client version: 1.13.0

```shell
(gdb) bt
#0  0x00000038e5a32495 in raise () from /lib64/libc.so.6
#1  0x00000038e5a33c75 in abort () from /lib64/libc.so.6
#2  0x00007f73a98b77ba in memcached_set_error (self=..., rc=MEMCACHED_ERRNO, at=0x7f73a98de53b "libmemcached/get.cc:205") at libmemcached/error.cc:316
#3  0x00007f73a98bbff8 in ascii_get_by_key (ptr=0x7f73a3ed1000, master_server_key=4294967295, is_group_key_set=false, key=0x7f7270678868 "***************", key_length=22)
    at libmemcached/get.cc:205
#4  0x00007f73a98bcbab in memcached_get_by_key (ptr=0x7f73a3ed1000, group_key=0x0, group_key_length=0, key=0x7f7270678868 "**************", key_length=22, 
    value_length=0x7f738b7f5ed8, flags=0x7f738b7f5ee0, error=0x7f738b7f5ee4) at libmemcached/get.cc:541
#5  0x00007f73a98bd12c in memcached_get (ptr=0x7f73a3ed1000, key=0x7f7270678868 "****************", key_length=22, value_length=0x7f738b7f5ed8, flags=0x7f738b7f5ee0, 
    error=0x7f738b7f5ee4) at libmemcached/get.cc:643
Segmentation fault

(gdb) f 3
#3  0x00007f73a98bbff8 in ascii_get_by_key (ptr=0x7f73a3ed1000, master_server_key=4294967295, is_group_key_set=false, key=0x7f7270678868 "***************", key_length=22)
    at libmemcached/get.cc:205
205     in libmemcached/get.cc
(gdb) p rc
$5 = MEMCACHED_ERRNO
(gdb) p server_key
$6 = 10
(gdb) p command
$7 = 0x7f73a98de533 "get "
(gdb) p vector
$8 = {{length = 4, buffer = 0x7f73a98de533}, {length = 0, buffer = 0x0}, {length = 22, buffer = 0x7f7270678868}, {length = 2, buffer = 0x7f73a98de538}}

(gdb) p *instance
$10 = {options = {is_allocated = false, is_initialized = true, is_shutting_down = false, is_dead = false}, number_of_hosts = 0, cursor_active = 0, port = 11247, fd = -1, 
  io_bytes_sent = 0, server_failure_counter = 1, server_failure_counter_query_id = 2, weight = 1, version = 11, state = MEMCACHED_SERVER_STATE_IN_TIMEOUT, io_wait_count = {read = 0, 
    write = 0}, major_version = 255 '\377', minor_version = 255 '\377', micro_version = 255 '\377', is_enterprise = false, type = MEMCACHED_CONNECTION_TCP, read_ptr = 0x7f728b4abfd8 "", 
  read_buffer_length = 0, read_data_length = 0, write_buffer_offset = 0, address_info = 0x7f72706f6300, address_info_next = 0x7f72706f6300, next_retry = 1, immediate_reconnect = false, 
  groupindex = -1, next = 0x0, root = 0x7f73a3ed1000, limit_maxbytes = 0, error_messages = 0x7f729906f800, read_buffer = '\000' <repeats 8195 times>, 
  write_buffer = "version\r\n", '\000' <repeats 8186 times>, hostname = "127.0.0.1", '\000' <repeats 1010 times>}

(gdb) p *(instance->error_messages)
$11 = {root = 0x7f73a3ed1000, query_id = 2, next = 0x0, rc = MEMCACHED_ERRNO, local_errno = 104, size = 148, 
  message = "[2021-07-06 11:36:14.528575] mc_id:27 mc_qid:2 er_qid:2 SYSTEM ERROR(Connection reset by peer), host: 127.0.0.1:11247 -> libmemcached/io.cc:501"}

```

```c
static memcached_return_t ascii_get_by_key(memcached_st *ptr,
                                           uint32_t master_server_key,
                                           bool is_group_key_set,
                                           const char *key,
                                           const size_t key_length)
{
  memcached_return_t rc;
  memcached_server_write_instance_st instance;
  uint32_t server_key;

  if (is_group_key_set)
  {
    server_key= master_server_key;
  }
  else
  {
    server_key= memcached_generate_hash_with_redistribution(ptr, key, key_length);
  }
  instance= memcached_server_instance_fetch(ptr, server_key);

  const char *command= (ptr->flags.support_cas ? "gets " : "get ");
  struct libmemcached_io_vector_st vector[]=
  {
    { strlen(command), command },
    { memcached_array_size(ptr->_namespace), memcached_array_string(ptr->_namespace) },
    { key_length, key },
    { 2, "\r\n" }
  };

  rc= memcached_vdo(instance, vector, 4, true);
  if (memcached_failed(rc))
  {
    memcached_io_reset(instance);
    memcached_set_error(*ptr, rc, MEMCACHED_AT);   /******core at this line, because of rc is MEMCACHED_ERRNO*********/
  }
  return rc;
}
```

**Comment by jhpark816** [comment]
@Chao-Zeng 
Thanks for raising this isssue.
Arcus c client maintains a list of errros that occurred in request processing.
The MEMCACHED_ERRNO is an error already registered in this error list.
To discover re-registeration of this error, the assert condition exists.
We currently solved this problem by making the error is returned without re-registration
instead of assert condition.
- commit link: https://github.com/naver/arcus-c-client/commit/6fbd17362837faa55cc9b8b04695fd162dd1fbf6

As the Arcus C client is is based on an old libmemcached version, its error handling is not yet complete. 
We are planning to update this error handling in the future. Please refer to it.

And, new arcus-c-client 1.13.1 is released, now.
Download and use it.

**Comment by Chao-Zeng** [comment]
thanks for quick fix
